import os
from datetime import datetime
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE

def add_heading(doc, text, level=1, color=None):
    heading = doc.add_heading(text, level=level)
    if color:
        for run in heading.runs:
            run.font.color.rgb = RGBColor(*color)
    return heading

def add_colored_paragraph(doc, label, value, label_color=(0, 0, 0)):
    p = doc.add_paragraph()
    run_label = p.add_run(f"{label}: ")
    run_label.bold = True
    run_label.font.color.rgb = RGBColor(*label_color)
    p.add_run(str(value))
    return p

def add_section_divider(doc):
    doc.add_paragraph("─" * 60)

def get_verdict_color(verdict):
    if verdict == "PURSUE":
        return (0, 128, 0)      # Green
    elif verdict == "HOLD":
        return (255, 140, 0)    # Orange
    else:
        return (200, 0, 0)      # Red

def generate_dossier(
    company_name: str,
    domain: str,
    client_info: str,
    bull_output: dict,
    bear_output: dict,
    detective_output: dict,
    orchestrator_output: dict
) -> str:
    doc = Document()

    # ── Page Setup ──
    section = doc.sections[0]
    section.page_width = Inches(8.5)
    section.page_height = Inches(11)
    section.left_margin = Inches(1)
    section.right_margin = Inches(1)
    section.top_margin = Inches(1)
    section.bottom_margin = Inches(1)

    verdict = orchestrator_output.get("verdict", "UNKNOWN")
    verdict_color = get_verdict_color(verdict)
    confidence = orchestrator_output.get("confidence", "N/A")
    regret = orchestrator_output.get("regretScore", {})
    generated_date = datetime.now().strftime("%B %d, %Y at %I:%M %p")

    # ── Cover Header ──
    title = doc.add_heading("ALLYVEX", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in title.runs:
        run.font.color.rgb = RGBColor(30, 30, 30)
        run.font.size = Pt(28)

    subtitle = doc.add_paragraph("Autonomous Strategic Sales Intelligence Report")
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle.runs[0].font.size = Pt(12)
    subtitle.runs[0].font.color.rgb = RGBColor(100, 100, 100)

    doc.add_paragraph("")

    # ── Target Company ──
    target_heading = doc.add_paragraph()
    target_heading.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = target_heading.add_run(f"Target Company: {company_name}")
    run.bold = True
    run.font.size = Pt(16)

    domain_para = doc.add_paragraph()
    domain_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    domain_para.add_run(domain).font.color.rgb = RGBColor(80, 80, 80)

    doc.add_paragraph("")

    # ── Verdict Badge ──
    verdict_para = doc.add_paragraph()
    verdict_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    verdict_run = verdict_para.add_run(f"VERDICT: {verdict}")
    verdict_run.bold = True
    verdict_run.font.size = Pt(20)
    verdict_run.font.color.rgb = RGBColor(*verdict_color)

    conf_para = doc.add_paragraph()
    conf_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    conf_para.add_run(
        f"Confidence: {confidence}/100   |   "
        f"Regret Score: {regret.get('score', 'N/A')}/100"
    ).font.size = Pt(11)

    regret_para = doc.add_paragraph()
    regret_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    regret_para.add_run(
        f"{regret.get('reason', '')}"
    ).font.color.rgb = RGBColor(80, 80, 80)

    doc.add_paragraph("")
    date_para = doc.add_paragraph()
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    date_para.add_run(
        f"Generated by ALLYVEX on {generated_date}"
    ).font.color.rgb = RGBColor(150, 150, 150)

    add_section_divider(doc)
    doc.add_page_break()

    # ════════════════════════════════════════
    # SECTION 1: EXECUTIVE SUMMARY
    # ════════════════════════════════════════
    add_heading(doc, "1. Executive Summary", level=1)
    doc.add_paragraph(
        orchestrator_output.get("executiveSummary", "No summary available.")
    )

    doc.add_paragraph("")
    add_colored_paragraph(doc, "Verdict", verdict, label_color=verdict_color)
    add_colored_paragraph(doc, "Confidence Level", f"{confidence}/100")
    add_colored_paragraph(
        doc, "Regret Score",
        f"{regret.get('score', 'N/A')}/100 — {regret.get('reason', '')}"
    )

    # ════════════════════════════════════════
    # SECTION 2: CLIENT ADVANTAGES & DISADVANTAGES
    # ════════════════════════════════════════
    doc.add_page_break()
    add_heading(doc, "2. Client Position Analysis", level=1)

    add_heading(doc, "Advantages Our Client Holds", level=2)
    advantages = orchestrator_output.get("clientAdvantages", [])
    for adv in advantages:
        p = doc.add_paragraph(style="List Bullet")
        p.add_run(adv)

    doc.add_paragraph("")
    add_heading(doc, "Disadvantages & Obstacles", level=2)
    disadvantages = orchestrator_output.get("clientDisadvantages", [])
    for dis in disadvantages:
        p = doc.add_paragraph(style="List Bullet")
        p.add_run(dis)

    # ════════════════════════════════════════
    # SECTION 3: DECIDING FACTORS
    # ════════════════════════════════════════
    doc.add_paragraph("")
    add_heading(doc, "3. Key Deciding Factors", level=1)

    factors = orchestrator_output.get("decidingFactors", {})

    add_heading(doc, "Technical Debt Assessment", level=2)
    doc.add_paragraph(
        factors.get("technicalDebtVerdict", "No assessment available.")
    )

    add_heading(doc, "Fiscal Pressure Assessment", level=2)
    doc.add_paragraph(
        factors.get("fiscalPressureVerdict", "No assessment available.")
    )

    add_heading(doc, "Recent Pivot Assessment", level=2)
    doc.add_paragraph(
        factors.get("pivotVerdict", "No assessment available.")
    )

    add_heading(doc, "Key Swing Factor", level=2)
    swing = doc.add_paragraph(
        factors.get("keySwingFactor", "No swing factor identified.")
    )
    swing.runs[0].bold = True

    # ════════════════════════════════════════
    # SECTION 4: BULL AGENT FINDINGS
    # ════════════════════════════════════════
    doc.add_page_break()
    add_heading(doc, "4. Bull Agent Findings — The Case FOR Pursuing", level=1)

    bull_score = bull_output.get("overallBullScore", "N/A")
    doc.add_paragraph(
        f"Bull Score: {bull_score}/100 — "
        f"{bull_output.get('keyArgument', '')}"
    )

    # Client relevant signals
    add_heading(doc, "Client-Relevant Buying Signals", level=2)
    for signal in bull_output.get("clientRelevantSignals", []):
        p = doc.add_paragraph(style="List Bullet")
        run = p.add_run(f"[{signal.get('strength', '')}] {signal.get('signal', '')}")
        run.bold = True
        p.add_run(f"\n    Why it matters: {signal.get('clientConnection', '')}")
        p.add_run(f"\n    Source: {signal.get('source', 'N/A')}")

    # Technical debt signals
    tech_signals = bull_output.get("technicalDebtSignals", [])
    if tech_signals:
        add_heading(doc, "Technical Debt Opportunities", level=2)
        for ts in tech_signals:
            p = doc.add_paragraph(style="List Bullet")
            p.add_run(ts.get("observation", "")).bold = True
            p.add_run(f"\n    How our client helps: {ts.get('howClientHelps', '')}")

    # Fiscal pressure signals
    fiscal_signals = bull_output.get("fiscalPressureSignals", [])
    if fiscal_signals:
        add_heading(doc, "Fiscal Pressure Opportunities", level=2)
        for fs in fiscal_signals:
            p = doc.add_paragraph(style="List Bullet")
            p.add_run(fs.get("observation", "")).bold = True
            p.add_run(f"\n    How our client helps: {fs.get('howClientHelps', '')}")

    # Pivot signals
    pivot_signals = bull_output.get("recentPivotSignals", [])
    if pivot_signals:
        add_heading(doc, "Recent Pivot Opportunities", level=2)
        for ps in pivot_signals:
            p = doc.add_paragraph(style="List Bullet")
            p.add_run(ps.get("observation", "")).bold = True
            p.add_run(
                f"\n    New requirement created: {ps.get('newRequirement', '')}"
            )
            p.add_run(f"\n    Client fit: {ps.get('clientFit', '')}")

    # ════════════════════════════════════════
    # SECTION 5: BEAR AGENT FINDINGS
    # ════════════════════════════════════════
    doc.add_page_break()
    add_heading(doc, "5. Bear Agent Findings — The Case AGAINST Pursuing", level=1)

    bear_score = bear_output.get("overallBearScore", "N/A")
    doc.add_paragraph(
        f"Bear Score: {bear_score}/100 — "
        f"{bear_output.get('keyArgument', '')}"
    )

    deal_killer = bear_output.get("dealKiller")
    if deal_killer:
        p = doc.add_paragraph()
        run = p.add_run(f"DEAL KILLER: {deal_killer}")
        run.bold = True
        run.font.color.rgb = RGBColor(200, 0, 0)

    add_heading(doc, "Client-Relevant Red Flags", level=2)
    for flag in bear_output.get("clientRelevantRedFlags", []):
        p = doc.add_paragraph(style="List Bullet")
        run = p.add_run(f"[{flag.get('severity', '')}] {flag.get('flag', '')}")
        run.bold = True
        p.add_run(f"\n    Impact on client: {flag.get('clientImpact', '')}")
        p.add_run(f"\n    Source: {flag.get('source', 'N/A')}")

    tech_barriers = bear_output.get("technicalDebtBarriers", [])
    if tech_barriers:
        add_heading(doc, "Technical Debt Barriers", level=2)
        for tb in tech_barriers:
            p = doc.add_paragraph(style="List Bullet")
            p.add_run(tb.get("observation", "")).bold = True
            p.add_run(
                f"\n    Integration risk: {tb.get('integrationRisk', '')}"
            )

    fiscal_barriers = bear_output.get("fiscalPressureBarriers", [])
    if fiscal_barriers:
        add_heading(doc, "Fiscal Pressure Barriers", level=2)
        for fb in fiscal_barriers:
            p = doc.add_paragraph(style="List Bullet")
            p.add_run(fb.get("observation", "")).bold = True
            p.add_run(f"\n    Budget risk: {fb.get('budgetRisk', '')}")

    # ════════════════════════════════════════
    # SECTION 6: DETECTIVE AUDIT
    # ════════════════════════════════════════
    doc.add_page_break()
    add_heading(doc, "6. Detective Agent Audit — Evidence Quality Review", level=1)

    bull_audit = detective_output.get("bullAudit", {})
    bear_audit = detective_output.get("bearAudit", {})
    client_fit = detective_output.get("clientFitAssessment", {})

    add_heading(doc, "Evidence Quality Scores", level=2)
    add_colored_paragraph(
        doc, "Bull Evidence Score",
        f"{bull_audit.get('evidenceScore', 'N/A')}/100"
    )
    add_colored_paragraph(
        doc, "Bear Evidence Score",
        f"{bear_audit.get('evidenceScore', 'N/A')}/100"
    )
    add_colored_paragraph(
        doc, "Overall Debate Confidence",
        f"{detective_output.get('overallConfidenceInDebate', 'N/A')}/100"
    )

    add_heading(doc, "Client Fit Assessment", level=2)
    table = doc.add_table(rows=4, cols=3)
    table.style = "Table Grid"
    headers = table.rows[0].cells
    headers[0].text = "Dimension"
    headers[1].text = "Rating"
    headers[2].text = "Reason"
    for cell in headers:
        for para in cell.paragraphs:
            for run in para.runs:
                run.bold = True

    fit_rows = [
        ("Technical Fit", client_fit.get("technicalFit", "N/A"),
         client_fit.get("technicalFitReason", "")),
        ("Budget Fit", client_fit.get("budgetFit", "N/A"),
         client_fit.get("budgetFitReason", "")),
        ("Timing Fit", client_fit.get("timingFit", "N/A"),
         client_fit.get("timingFitReason", ""))
    ]
    for i, (dim, rating, reason) in enumerate(fit_rows, 1):
        row = table.rows[i].cells
        row[0].text = dim
        row[1].text = rating
        row[2].text = reason

    add_heading(doc, "Critical Overlooked Fact", level=2)
    doc.add_paragraph(
        detective_output.get("criticalOverlookedFact", "None identified.")
    )

    missing = detective_output.get("missingContext", [])
    if missing:
        add_heading(doc, "Missing Context Found", level=2)
        for mc in missing:
            p = doc.add_paragraph(style="List Bullet")
            p.add_run(mc.get("finding", "")).bold = True
            p.add_run(
                f"\n    Impact: {mc.get('impact', '')} — "
                f"{mc.get('clientRelevance', '')}"
            )

    # ════════════════════════════════════════
    # SECTION 7: OUTREACH STRATEGY
    # ════════════════════════════════════════
    doc.add_page_break()
    add_heading(doc, "7. Outreach Strategy", level=1)

    dm = orchestrator_output.get("targetDecisionMaker", {})
    add_heading(doc, "Target Decision Maker", level=2)
    add_colored_paragraph(doc, "Title", dm.get("title", "N/A"))
    add_colored_paragraph(doc, "Why This Person", dm.get("why", "N/A"))
    add_colored_paragraph(
        doc, "LinkedIn Search", dm.get("linkedinSearchTip", "N/A")
    )

    email = orchestrator_output.get("outreachEmail", {})
    add_heading(doc, "Outreach Email Draft", level=2)
    add_colored_paragraph(doc, "Subject", email.get("subject", "N/A"))
    doc.add_paragraph("")
    body_para = doc.add_paragraph(email.get("body", "No email generated."))
    body_para.style.font.size = Pt(10)

    add_heading(doc, "Proposed Next Steps", level=2)
    for step in orchestrator_output.get("proposedNextSteps", []):
        p = doc.add_paragraph(style="List Number")
        p.add_run(step)

    if verdict == "HOLD" and orchestrator_output.get("ifHold"):
        add_heading(doc, "Re-evaluation Trigger", level=2)
        doc.add_paragraph(orchestrator_output.get("ifHold"))

    if verdict == "AVOID" and orchestrator_output.get("ifAvoid"):
        add_heading(doc, "Conditions to Revisit", level=2)
        doc.add_paragraph(orchestrator_output.get("ifAvoid"))

    # ════════════════════════════════════════
    # FOOTER
    # ════════════════════════════════════════
    add_section_divider(doc)
    footer_para = doc.add_paragraph(
        f"This report was generated autonomously by ALLYVEX on {generated_date}. "
        f"All intelligence was gathered from public sources via live web search. "
        f"This document is confidential and intended for internal sales use only."
    )
    footer_para.runs[0].font.color.rgb = RGBColor(150, 150, 150)
    footer_para.runs[0].font.size = Pt(9)

    # ── Save ──
    os.makedirs("outputs", exist_ok=True)
    filename = (
        f"ALLYVEX_{company_name.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"
    )
    filepath = f"outputs/{filename}"
    doc.save(filepath)
    print(f"  [DOCUMENT] Dossier saved: {filepath}")
    return filename